### PR TITLE
Port to GNOME 45

### LINKED ISSUE #8: GNOME 45 support
Port the extension to GNOME 45.

https://gjs.guide/extensions/upgrading/gnome-shell-45.html

### PR DESCRIPTION
**Pull request by Lihis**
Closes #8

### CODE REVIEW

**Comment by Lihis** [comment]
Currently the extension loads and the preferences can be managed.

Still need to test the extension a bit as I originally made this in `master` branch (that's why created this as a draft). So far it seemed to properly set the airplane mode after a reboot but wouldn't mind if someone else also confirms this to work properly, then I'll could remove the draft status.

Edit: Also I don't have prior experience with extension development so review with care

**Comment by AntiKippi** [comment]
Thank you very much for you contribution!

Just got to test it and noticed some things:
  1. When having all switches off, you cannot disable airplane mode. This might not be related to your code changes but to changes in the behavior of the gnome-shell.
  2. Not enabling airplane mode when disabling Wi-Fi as the last active radio is broken.
  3. The code has some typos

Gonna investigate this now.

**Comment by AntiKippi** [comment]
Ah the cause of the issues was switching from `await NM.Client.new_async(null);` to `NM.Client.new(null);` (The async is there for a reason ;)). Fixed it and it works good enough for the dev branch now, gonna merge this.

**Comment by Lihis** [comment]
> Ah the cause of the issues was switching from `await NM.Client.new_async(null);` to `NM.Client.new(null);` (The async is there for a reason ;)). Fixed it and it works good enough for the dev branch now, gonna merge this.

Oops.. I think I got some error about the async and as after that was still so many errors to fix that I forgot to revisit it.

And thanks for taking a look and fixing the leftover issues!

**Pull request merged**
